/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "RX.h"
#include "RX_aliases.h"
#include "TX.h"
#include "TX_aliases.h"
#include "UART.h"
#include "RST.h"
#include "RST_aliases.h"
#include "Rx_Int.h"
#include "USB_UART.h"
#include "USB_UART_SPI_UART.h"
#include "USB_UART_PINS.h"
#include "USB_UART_SPI_UART_PVT.h"
#include "USB_UART_PVT.h"
#include "USB_UART_BOOT.h"
#include "UART_IntClock.h"
#include "USB_UART_SCBCLK.h"
#include "USB_UART_tx.h"
#include "USB_UART_tx_aliases.h"
#include "USB_UART_SCB_IRQ.h"
#include "USB_UART_rx.h"
#include "USB_UART_rx_aliases.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

