# THIS FILE IS AUTOMATICALLY GENERATED
# Project: \\myhome01.spu.edu\users\tdoan1\Documents\PSoC Creator\PSoC 4 Wi-Fi Module tEst\PSoC 4 Wi-Fi Module Test.cydsn\PSoC 4 Wi-Fi Module Test.cyprj
# Date: Wed, 29 Jan 2020 04:04:29 GMT
#set_units -time ns
create_clock -name {USB_UART_SCBCLK(FFB)} -period 708.33333333333326 -waveform {0 354.166666666667} [list [get_pins {ClockBlock/ff_div_3}]]
create_clock -name {CyRouted1} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFClk} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFClk} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySysClk} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/sysclk}]]
create_generated_clock -name {UART_IntClock} -source [get_pins {ClockBlock/hfclk}] -edges {1 13 27} -nominal_period 541.66666666666663 [list [get_pins {ClockBlock/udb_div_0}]]
create_generated_clock -name {USB_UART_SCBCLK} -source [get_pins {ClockBlock/hfclk}] -edges {1 17 35} -nominal_period 708.33333333333326 [list]


# Component constraints for \\myhome01.spu.edu\users\tdoan1\Documents\PSoC Creator\PSoC 4 Wi-Fi Module tEst\PSoC 4 Wi-Fi Module Test.cydsn\TopDesign\TopDesign.cysch
# Project: \\myhome01.spu.edu\users\tdoan1\Documents\PSoC Creator\PSoC 4 Wi-Fi Module tEst\PSoC 4 Wi-Fi Module Test.cydsn\PSoC 4 Wi-Fi Module Test.cyprj
# Date: Wed, 29 Jan 2020 04:04:08 GMT
